/**
 * Aurora Music Player - Track Metadata, Translations & Multi-Language Data
 * Includes 16+ Royalty-Free Tracks (English, Hindi & Tamil) with Dual-Language Synced Lyrics
 */

const AURORA_DATA = {
  tracks: [
    // --- TAMIL SONGS (5 TRACKS) ---
    {
      id: "track-ta-1",
      title: "Kannamma (Kanmani)",
      artist: "Anirudh Synth Ensemble",
      album: "Tamil Romantic Reverie",
      genre: "Tamil Melody / Fusion",
      lang: "ta",
      duration: 220, // 3:40
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gta1' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23f59e0b'/><stop offset='100%25' stop-color='%23b45309'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gta1)'/><circle cx='200' cy='180' r='100' fill='none' stroke='%23fef08a' stroke-width='4' opacity='0.4'/><circle cx='200' cy='180' r='60' fill='%2378350f'/><text x='200' y='330' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='24'>கண்ணம்மா</text><text x='200' y='360' text-anchor='middle' fill='%23fef08a' font-family='sans-serif' font-size='16'>Kannamma Melody</text></svg>",
      dominantColor: "#f59e0b",
      accentColor: "#fef08a",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/02/07/audio_d0713b1946.mp3?filename=relaxing-guitar-loop-11234.mp3",
      syntheticFreq: [293.66, 329.63, 370.00, 440.00, 554.37],
      lyrics: [
        { time: 0, text: "♪ (புல்லாங்குழல் & வீணை இசை - Flute & Veena Intro...)", translation: "♪ (Flute & Veena Acoustic Prelude...)" },
        { time: 15, text: "கண்ணம்மா உன்னைக் காணும் நேரம்", translation: "Kannamma, the moment I gaze at you" },
        { time: 32, text: "நெஞ்சினில் பாயுதே புது காவியம்", translation: "A new poetic harmony flows through my heart" },
        { time: 50, text: "தென்றல் தீண்டும் பொன் மாலை வேளை", translation: "In the golden evening touched by gentle breeze" },
        { time: 70, text: "உன் சிரிப்பில் என் உலகம் மலருதே", translation: "My whole world blooms inside your smile" },
        { time: 95, text: "♪ (இனிய பாசிட்டிவ் மெலடி இசை - Soulful Melody...)", translation: "♪ (Soulful Instrumental Interlude...)" },
        { time: 120, text: "விண்மீன்கள் பேசும் இரவினில் நாம்", translation: "Under the night sky where stars speak to us" },
        { time: 150, text: "என்றென்றும் இணைந்திருக்கும் உயிரென", translation: "As two souls bound together forevermore" },
        { time: 185, text: "கண்ணம்மா... என் கண்ணம்மா...", translation: "Kannamma... my beloved Kannamma..." }
      ]
    },
    {
      id: "track-ta-2",
      title: "Maayavi (Elixir of Night)",
      artist: "AR Cyber Symphony",
      album: "Kollywood Future Beats",
      genre: "Tamil Synthwave",
      lang: "ta",
      duration: 210, // 3:30
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gta2' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%238b5cf6'/><stop offset='100%25' stop-color='%23ec4899'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gta2)'/><polygon points='200,80 280,240 120,240' fill='%23ffffff' opacity='0.3'/><text x='200' y='330' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='24'>மாயாவி</text><text x='200' y='360' text-anchor='middle' fill='%23f472b6' font-family='sans-serif' font-size='16'>Maayavi Cyber Beat</text></svg>",
      dominantColor: "#8b5cf6",
      accentColor: "#ec4899",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=lofi-study-112191.mp3",
      syntheticFreq: [220.00, 261.63, 329.63, 392.00],
      lyrics: [
        { time: 0, text: "♪ (மின்சார விசை இசை - Electronic Synth Beats...)", translation: "♪ (Electric Synth Beats...)" },
        { time: 18, text: "இரவின் நிழலில் மாயாவி நீ", translation: "You are the illusionist in the night shadows" },
        { time: 38, text: "மின்சார அலைகளில் மிதக்கும் கனவு", translation: "A dream floating on electric waves" },
        { time: 60, text: "நகரத்தின் விளக்குகள் எரியும் போது", translation: "When city lights ignite the darkness" },
        { time: 85, text: "உன் குரல் மட்டும் என் காதில் ஒலிக்கும்", translation: "Your voice echoes alone in my ears" },
        { time: 120, text: "♪ (ஹை எனர்ஜி பீட் - High Energy Drop...)", translation: "♪ (Synth Drop & Bassline...)" },
        { time: 155, text: "மாயாவி... என் மாயாவி...", translation: "Maayavi... my enchanting illusion..." }
      ]
    },
    {
      id: "track-ta-3",
      title: "Kadhale Kadhale Chill",
      artist: "Madras Lofi Collective",
      album: "Beachside Chennai Chill",
      genre: "Tamil Lofi Chill",
      lang: "ta",
      duration: 195, // 3:15
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gta3' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%2306b6d4'/><stop offset='100%25' stop-color='%23047857'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gta3)'/><circle cx='200' cy='200' r='80' fill='%2367e8f9' opacity='0.4'/><text x='200' y='330' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='24'>காதலே காதலே</text><text x='200' y='360' text-anchor='middle' fill='%23a7f3d0' font-family='sans-serif' font-size='16'>Kadhale Lofi Vibe</text></svg>",
      dominantColor: "#06b6d4",
      accentColor: "#34d399",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=chill-lofi-song-8444.mp3",
      syntheticFreq: [196.00, 246.94, 293.66, 392.00],
      lyrics: [
        { time: 0, text: "♪ (கடல் அலை சப்தம் & லோஃபி பீட்...)", translation: "♪ (Sea Waves ambience & Lofi beats...)" },
        { time: 16, text: "மரைனா கரையில் மாலைக் காற்று", translation: "Evening breeze upon the Marina shore" },
        { time: 36, text: "காதலே காதலே என்ன செய்தாய்?", translation: "Oh love, what magic have you wrought?" },
        { time: 60, text: "மனதில் மெல்லிய அமைதி தருவாய்", translation: "Granting tender peace inside my soul" },
        { time: 90, text: "♪ (கிட்டார் மெல்லிசை - Soft Guitar Solo...)", translation: "♪ (Soft Acoustic Guitar Solo...)" },
        { time: 130, text: "அமைதியான இரவு நேர நினைவுகள்...", translation: "Serene night memories lingering..." }
      ]
    },
    {
      id: "track-ta-4",
      title: "Vaathi Folk Rhythm",
      artist: "Thaman Beats & Drums",
      album: "Folk Fusion Dhamaka",
      genre: "Tamil Folk Fusion",
      lang: "ta",
      duration: 215, // 3:35
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gta4' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23ef4444'/><stop offset='100%25' stop-color='%23f59e0b'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gta4)'/><circle cx='200' cy='190' r='90' fill='%23fef08a' opacity='0.3'/><text x='200' y='330' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='24'>வாத்தி ரிதம்</text><text x='200' y='360' text-anchor='middle' fill='%23fef08a' font-family='sans-serif' font-size='16'>Vaathi Folk Energy</text></svg>",
      dominantColor: "#ef4444",
      accentColor: "#f59e0b",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792e7.mp3?filename=energy-122703.mp3",
      syntheticFreq: [146.83, 220.00, 293.66, 370.00],
      lyrics: [
        { time: 0, text: "♪ (தப்பாட்டம் & கிராமிய தாளம்...)", translation: "♪ (Thappattam Folk Percussion Intro...)" },
        { time: 20, text: "அதிரும் தாளம் ஆடும் காலும்", translation: "Resonating beats and dancing feet" },
        { time: 42, text: "நாட்டுப்புறத்து உற்சாக ராகம்", translation: "Vibrant ragas straight from the heartland" },
        { time: 65, text: "வாத்தி ரிதம் துள்ள வைக்கும்!", translation: "Vaathi rhythm making everyone move!" },
        { time: 100, text: "♪ (துள்ளல் இசை பிரேக் - Energy Drop...)", translation: "♪ (Folk Energy Drop...)" },
        { time: 140, text: "ஆடு மகனே ஆடு கொண்டாடு!", translation: "Dance and celebrate together!" }
      ]
    },
    {
      id: "track-ta-5",
      title: "Singappenney Vibe",
      artist: "Isai Storm & Acoustic Ensemble",
      album: "Empowerment Anthems",
      genre: "Tamil Pop / Acoustic",
      lang: "ta",
      duration: 205, // 3:25
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gta5' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23ec4899'/><stop offset='100%25' stop-color='%236366f1'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gta5)'/><path d='M200,90 L230,170 L310,170 L245,215 L270,295 L200,245 L130,295 L155,215 L90,170 L170,170 Z' fill='%23ffffff' opacity='0.3'/><text x='200' y='340' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='24'>சிங்கப்பெண்ணே</text></svg>",
      dominantColor: "#ec4899",
      accentColor: "#6366f1",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/03/10/audio_c3e66f0e22.mp3?filename=hip-hop-rock-10389.mp3",
      syntheticFreq: [261.63, 329.63, 392.00, 523.25],
      lyrics: [
        { time: 0, text: "♪ (நம்பிக்கை தரும் இசை - Inspiring Chords...)", translation: "♪ (Inspiring Piano Chords...)" },
        { time: 18, text: "வானம் உந்தன் எல்லை இல்லையே", translation: "The sky is not your limit" },
        { time: 40, text: "எழுந்து வா சிங்கப்பெண்ணே", translation: "Rise up like a lioness" },
        { time: 65, text: "உன் பாதையில் வெற்றி காத்திருக்கு", translation: "Triumph awaits along your path" },
        { time: 110, text: "சிங்கப்பெண்ணே... நிமிர்த்து நில்...", translation: "Singappenney... stand tall with pride..." }
      ]
    },

    // --- HINDI SONGS (5 TRACKS) ---
    {
      id: "track-hi-1",
      title: "Tum Hi Ho Reverie",
      artist: "Mithoon Waves & Acoustic",
      album: "Bollywood Heartbeats",
      genre: "Hindi Acoustic / Romance",
      lang: "hi",
      duration: 230, // 3:50
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='ghi1' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23e11d48'/><stop offset='100%25' stop-color='%239f1239'/></linearGradient></defs><rect width='400' height='400' fill='url(%23ghi1)'/><circle cx='200' cy='180' r='90' fill='none' stroke='%23fecdd3' stroke-width='4' opacity='0.5'/><text x='200' y='330' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='24'>तुम ही हो</text><text x='200' y='360' text-anchor='middle' fill='%23fecdd3' font-family='sans-serif' font-size='16'>Tum Hi Ho Acoustic</text></svg>",
      dominantColor: "#e11d48",
      accentColor: "#fecdd3",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=ambient-piano-amp-strings-10711.mp3",
      syntheticFreq: [220.00, 261.63, 329.63, 392.00],
      lyrics: [
        { time: 0, text: "♪ (धीमी पियानो धुनों के साथ - Soft Piano Strings...)", translation: "♪ (Soft Acoustic Piano Strings...)" },
        { time: 18, text: "हम तेरे बिन अब रह नहीं सकते", translation: "I can no longer live without you" },
        { time: 38, text: "तेरे बिना क्या वजूद मेरा", translation: "Without you, what existence do I have?" },
        { time: 60, text: "तुझसे जुदा गर हो जाएंगे", translation: "If I ever get separated from you" },
        { time: 82, text: "तो खुद से ही हो जाएंगे जुदा", translation: "I would be separated from my own self" },
        { time: 110, text: "क्योंकि तुम ही हो, अब तुम ही हो", translation: "Because you are the one, now only you are the one" },
        { time: 140, text: "जिंदगी अब तुम ही हो...", translation: "My life is now only you..." }
      ]
    },
    {
      id: "track-hi-2",
      title: "Channa Mereya Echoes",
      artist: "Pritam Acoustic Sessions",
      album: "Sufi Pop Melodies",
      genre: "Hindi Sufi Pop",
      lang: "hi",
      duration: 225, // 3:45
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='ghi2' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23d97706'/><stop offset='100%25' stop-color='%2378350f'/></linearGradient></defs><rect width='400' height='400' fill='url(%23ghi2)'/><circle cx='200' cy='180' r='85' fill='%23fef08a' opacity='0.3'/><text x='200' y='330' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='24'>चन्ना मेरेया</text><text x='200' y='360' text-anchor='middle' fill='%23fef08a' font-family='sans-serif' font-size='16'>Channa Mereya Echoes</text></svg>",
      dominantColor: "#d97706",
      accentColor: "#fef08a",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/01/26/audio_d0c6b12a86.mp3?filename=golden-hour-piano-11451.mp3",
      syntheticFreq: [293.66, 369.99, 440.00, 587.33],
      lyrics: [
        { time: 0, text: "♪ (सूफी गिटार और शहनाई - Sufi Guitar & Shehnai...)", translation: "♪ (Sufi Acoustic Guitar & Shehnai...)" },
        { time: 20, text: "अच्छा चलता हूँ, दुआओं में याद रखना", translation: "Farewell then, keep me in your prayers" },
        { time: 42, text: "मेरे जिक्र का जुबां पे स्वाद रखना", translation: "Keep the taste of my name upon your lips" },
        { time: 68, text: "दिल के संदूकों में मेरे अच्छे काम रखना", translation: "Store my good deeds in the treasure box of your heart" },
        { time: 105, text: "ओ चन्ना मेरेया मेरेया बेलिया...", translation: "Oh my beloved moon, my dear friend..." }
      ]
    },
    {
      id: "track-hi-3",
      title: "Raataan Lambiyan Chill",
      artist: "Tanishk Chill Lofi",
      album: "Midnight Romance Hindi",
      genre: "Hindi Lofi Romance",
      lang: "hi",
      duration: 200, // 3:20
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='ghi3' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%236366f1'/><stop offset='100%25' stop-color='%23312e81'/></linearGradient></defs><rect width='400' height='400' fill='url(%23ghi3)'/><polygon points='200,60 230,140 310,140 245,190 270,270 200,220 130,270 155,190 90,140 170,140' fill='%23a5b4fc' opacity='0.5'/><text x='200' y='330' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='24'>रातां लम्बियां</text></svg>",
      dominantColor: "#6366f1",
      accentColor: "#a5b4fc",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/05/16/audio_c2278440d4.mp3?filename=rainy-lofi-10901.mp3",
      syntheticFreq: [220.00, 261.63, 329.63, 392.00],
      lyrics: [
        { time: 0, text: "♪ (लोफ़ाई बीट और बारिश की आवाज़...)", translation: "♪ (Lofi Beats & Rain Ambience...)" },
        { time: 16, text: "तेरी मेरी गल्लां हो गईं मशहूर", translation: "Our love story has become famous everywhere" },
        { time: 38, text: "करना कभी तू मुझे नजरों से दूर", translation: "Never cast me away from your sight" },
        { time: 62, text: "रातां लम्बियां लम्बियां रे, कटे तेरे संगियां रे", translation: "Long are the nights, spent in your sweet company" },
        { time: 100, text: "सुन दिल जानी, तू ही मेरी जिंदगानी...", translation: "Listen, beloved of my heart, you are my life..." }
      ]
    },
    {
      id: "track-hi-4",
      title: "Kabira Beats & Strings",
      artist: "Folk Fusion Band India",
      album: "Desi Chill Out",
      genre: "Hindi Folk Fusion",
      lang: "hi",
      duration: 210, // 3:30
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='ghi4' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%2310b981'/><stop offset='100%25' stop-color='%23064e3b'/></linearGradient></defs><rect width='400' height='400' fill='url(%23ghi4)'/><circle cx='200' cy='180' r='90' fill='none' stroke='%236ee7b7' stroke-width='4'/><text x='200' y='330' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='24'>कबीरा</text></svg>",
      dominantColor: "#10b981",
      accentColor: "#6ee7b7",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/03/10/audio_f535804555.mp3?filename=future-bass-10388.mp3",
      syntheticFreq: [164.81, 207.65, 246.94, 329.63],
      lyrics: [
        { time: 0, text: "♪ (संतूर और सारंगी - Santoor & Sarangi Strings...)", translation: "♪ (Santoor & Sarangi Instrumental Folk...)" },
        { time: 18, text: "रे कबीरा मान जा, रे फकीरा मान जा", translation: "Oh Kabira listen, oh wandering fakir accept this" },
        { time: 40, text: "आजा तुझको पुकारे तेरी परछाइयां", translation: "Come back, your own shadows call out to you" },
        { time: 68, text: "टूटी चारपाई वही, ठंडी पुरवाई वही", translation: "The same woven bed, the same cool breeze" },
        { time: 110, text: "कबीरा मान जा रे...", translation: "Kabira listen to your heart..." }
      ]
    },
    {
      id: "track-hi-5",
      title: "Kesariya Glow",
      artist: "Arijit Dance Waves",
      album: "Saffron Summer Hits",
      genre: "Hindi Electro Pop",
      lang: "hi",
      duration: 215, // 3:35
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='ghi5' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23f97316'/><stop offset='100%25' stop-color='%23ea580c'/></linearGradient></defs><rect width='400' height='400' fill='url(%23ghi5)'/><circle cx='200' cy='180' r='75' fill='%23fef08a' opacity='0.8'/><text x='200' y='330' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='24'>केसरिया</text></svg>",
      dominantColor: "#f97316",
      accentColor: "#fdba74",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/02/07/audio_d0713b1946.mp3?filename=relaxing-guitar-loop-11234.mp3",
      syntheticFreq: [261.63, 329.63, 392.00, 523.25],
      lyrics: [
        { time: 0, text: "♪ (केसरिया धुनों का सवेरा - Saffron Guitars...)", translation: "♪ (Saffron Guitar Intro...)" },
        { time: 18, text: "मुझको इतना बता दे कोई, कैसे तुझसे दिल न लगाए", translation: "Tell me someone, how can one not fall for you?" },
        { time: 42, text: "केसरिया तेरा इश्क है पिया, रंग जाऊं जो मैं हाथ लगाऊं", translation: "Your love is like saffron my dear, touching it colors my soul" },
        { time: 80, text: "दिन बीते सारा तेरी फिक्र में, रैन बीते तेरे ख्याल में", translation: "Day passes caring for you, night passes thinking of you" },
        { time: 120, text: "केसरिया तेरा इश्क है पिया...", translation: "Your love is like saffron my dear..." }
      ]
    },

    // --- ENGLISH SONGS (6 TRACKS) ---
    {
      id: "track-en-1",
      title: "Midnight City Lights",
      artist: "Aetheria",
      album: "Cybernetic Horizons",
      genre: "Synthwave",
      lang: "en",
      duration: 215, // 3:35
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gen1' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%236366f1'/><stop offset='100%25' stop-color='%23ec4899'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gen1)'/><circle cx='200' cy='200' r='120' fill='none' stroke='%23ffffff' stroke-width='4' opacity='0.3'/><circle cx='200' cy='200' r='80' fill='%230f172a' opacity='0.8'/><path d='M160 140 L260 200 L160 260 Z' fill='%23ffffff'/><text x='200' y='340' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='20'>Midnight City Lights</text></svg>",
      dominantColor: "#6366f1",
      accentColor: "#ec4899",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=lofi-study-112191.mp3",
      syntheticFreq: [261.63, 329.63, 392.00, 523.25],
      lyrics: [
        { time: 0, text: "♪ (Synthesizer intro playing...)", translation: "♪ (மின்சார விசை அறிமுக இசை / इलेक्ट्रॉनिक सिंथेसाइज़र)" },
        { time: 12, text: "Neon lights reflecting in the rain", translation: "மழையில் பிரதிபலிக்கும் நBooleanField விளக்குகள் / बारिश में चमकती नीयन रोशनी" },
        { time: 24, text: "Speeding through the empty highway lanes", translation: "வெற்று நெடுஞ்சாலையில் வேகமாகப் பயணிக்கிறேன் / खाली हाईवे पर रफ्तार से चलते हुए" },
        { time: 36, text: "Midnight city, lost inside the sound", translation: "நடுஇரவு நகரம், இசையில் தொலைந்தேன் / आधी रात का शहर, संगीत में खो गया" },
        { time: 48, text: "Where the future echoes all around", translation: "எதிர்காலம் எங்கும் எதிரொலிக்கும் இடம் / जहां भविष्य हर तरफ गूंजता है" },
        { time: 65, text: "♪ (Electro bass breakdown...)", translation: "♪ (எலக்ட்ரோ பேஸ் பிரேக்டவுன் / इलेक्ट्रो बेस)" },
        { time: 85, text: "Chasing shadows in the electric haze", translation: "மின்சாரப் புகையில் நிழல்களைத் துரத்துகிறேன் / बिजली के कोहरे में सायों का पीछा" },
        { time: 105, text: "Drifting through a retro-future maze", translation: "ரெட்ரோ-எதிர்காலப் பாதையில் மிதக்கிறேன் / एक रेट्रो-फ्यूचर भूलभुलैया में बहते हुए" },
        { time: 135, text: "Midnight city lights...", translation: "நடுஇரவு நகர விளக்குகள்... / आधी रात की शहर की रोशनी..." }
      ]
    },
    {
      id: "track-en-2",
      title: "Cosmic Drift",
      artist: "Starlight Echoes",
      album: "Orbital Reverie",
      genre: "Ambient Space",
      lang: "en",
      duration: 198, // 3:18
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gen2' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%230ea5e9'/><stop offset='100%25' stop-color='%236366f1'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gen2)'/><polygon points='200,60 240,160 350,160 260,220 300,330 200,260 100,330 140,220 50,160 160,160' fill='%23ffffff' opacity='0.4'/><text x='200' y='350' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='22'>Cosmic Drift</text></svg>",
      dominantColor: "#0ea5e9",
      accentColor: "#38bdf8",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=ambient-piano-amp-strings-10711.mp3",
      syntheticFreq: [220.00, 277.18, 329.63, 440.00],
      lyrics: [
        { time: 0, text: "♪ (Ambient cosmic pad swelling...)", translation: "♪ (விண்வெளி பிரபஞ்ச இசை / परिवेशी अंतरिक्ष संगीत)" },
        { time: 15, text: "Floating past distant galaxies", translation: "தொலைதூர விண்மீன் திரள்களைக் கடந்து மிதக்கிறேன் / दूर की आकाशगंगाओं से होकर तैरना" },
        { time: 30, text: "Weightless in the quiet starry sea", translation: "அமைதியான நட்சத்திரக் கடலில் எடையின்றி / शांत तारों भरे समुद्र में भारहीन" },
        { time: 50, text: "Time turns into endless light", translation: "காலம் முடிவில்லாத ஒளியாக மாறுகிறது / समय अनंत प्रकाश में बदल जाता है" },
        { time: 75, text: "Drifting slowly through the cosmic night", translation: "பிரபஞ்ச இரவில் மெதுவாக மிதக்கிறேன் / ब्रह्मांडीय रात में धीरे-धीरे बहना" },
        { time: 110, text: "♪ (Peaceful piano sequence...)", translation: "♪ (அமைதியான பியானோ இசை / शांत पियानो)" }
      ]
    },
    {
      id: "track-en-3",
      title: "Solar Flare",
      artist: "Nova Horizon",
      album: "Stellar Fusion",
      genre: "Electronic / Dance",
      lang: "en",
      duration: 242, // 4:02
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gen3' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%23f59e0b'/><stop offset='100%25' stop-color='%23ef4444'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gen3)'/><circle cx='200' cy='200' r='100' fill='%23ffffff' opacity='0.25'/><circle cx='200' cy='200' r='60' fill='%23fef08a'/><text x='200' y='350' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='22'>Solar Flare</text></svg>",
      dominantColor: "#f59e0b",
      accentColor: "#ef4444",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792e7.mp3?filename=energy-122703.mp3",
      syntheticFreq: [146.83, 220.00, 293.66, 370.00],
      lyrics: [
        { time: 0, text: "♪ (High energy synth beat...)", translation: "♪ (அதிவேக எலக்ட்ரானிக் பீட் / उच्च ऊर्जा सिंथ बीट)" },
        { time: 20, text: "Ignite the spark inside the flame", translation: "சுடருக்குள் இருக்கும் பொறியை மூட்டு / ज्वाला के अंदर की चिंगारी को जलाएं" },
        { time: 40, text: "Feel the pulse, remember the name", translation: "துடிப்பை உணர், பெயரை நினைவில் கொள் / धड़कन को महसूस करें, नाम याद रखें" },
        { time: 60, text: "Solar flare burning bright!", translation: "சூரிய சுடர் பிரகாசமாக எரிகிறது! / सौर ज्वाला चमकदार जल रही है!" },
        { time: 90, text: "♪ (Heavy bass drop...)", translation: "♪ (ஹெவி பேஸ் டிராப் / भारी बास ड्रॉप)" }
      ]
    },
    {
      id: "track-en-4",
      title: "Emerald Forest Chill",
      artist: "Solstice Collective",
      album: "Organic Vibes",
      genre: "Lofi / Downtempo",
      lang: "en",
      duration: 180, // 3:00
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gen4' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%2310b981'/><stop offset='100%25' stop-color='%23047857'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gen4)'/><path d='M200 80 L280 260 L120 260 Z' fill='%23ffffff' opacity='0.3'/><path d='M200 140 L260 280 L140 280 Z' fill='%23a7f3d0' opacity='0.5'/><text x='200' y='350' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='20'>Emerald Forest Chill</text></svg>",
      dominantColor: "#10b981",
      accentColor: "#34d399",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=chill-lofi-song-8444.mp3",
      syntheticFreq: [196.00, 246.94, 293.66, 392.00],
      lyrics: [
        { time: 0, text: "♪ (Vinyl crackle & lofi beats...)", translation: "♪ (லோஃபி பீட்ஸ் மற்றும் இயற்கை சப்தம் / ललोफी बीट्स)" },
        { time: 15, text: "Morning rain upon the leaves", translation: "இலைகள் மீது காலை மழை / पत्तियों पर सुबह की बारिश" },
        { time: 35, text: "Gentle breeze among the trees", translation: "மரங்களுக்கிடையே மெல்லிய தென்றல் / पेड़ों के बीच हल्की हवा" },
        { time: 60, text: "Relaxing in the emerald shade", translation: "மரகத நிழலில் ஓய்வெடுக்கிறேன் / पन्ने की छाया में आराम करते हुए" }
      ]
    },
    {
      id: "track-en-5",
      title: "Velvet Groove",
      artist: "The Silk Ensemble",
      album: "Midnight Lounge",
      genre: "Nu-Jazz & Soul",
      lang: "en",
      duration: 210, // 3:30
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gen5' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%238b5cf6'/><stop offset='100%25' stop-color='%236b21a8'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gen5)'/><circle cx='200' cy='180' r='90' stroke='%23f3e8ff' stroke-width='6' fill='none'/><rect x='150' y='280' width='100' height='10' rx='5' fill='%23ffffff'/><text x='200' y='340' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='22'>Velvet Groove</text></svg>",
      dominantColor: "#8b5cf6",
      accentColor: "#a855f7",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/03/10/audio_c3e66f0e22.mp3?filename=hip-hop-rock-10389.mp3",
      syntheticFreq: [174.61, 220.00, 261.63, 349.23],
      lyrics: [
        { time: 0, text: "♪ (Smooth saxophone intro...)", translation: "♪ (மென்மையான சேக்ஸாபோன் இசை / चिकना सैक्सोफोन)" },
        { time: 20, text: "Late night jazz in a quiet club", translation: "அமைதியான கிளப்பில் நள்ளிரவு ஜாஸ் / शांत क्लब में देर रात का जैज" },
        { time: 45, text: "Velvet rhythms and bass soft thuds", translation: "வெல்வெட் தாளங்கள் மற்றும் மெல்லிய பேஸ் / मखमली लय और बास की आवाज" }
      ]
    },
    {
      id: "track-en-6",
      title: "Ocean Wave Serenade",
      artist: "Kalea Shores",
      album: "Pacific Reverie",
      genre: "Acoustic Chill",
      lang: "en",
      duration: 195, // 3:15
      cover: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 400 400'><defs><linearGradient id='gen6' x1='0' y1='0' x2='1' y2='1'><stop offset='0%25' stop-color='%2306b6d4'/><stop offset='100%25' stop-color='%230284c7'/></linearGradient></defs><rect width='400' height='400' fill='url(%23gen6)'/><path d='M 0,200 Q 100,160 200,200 T 400,200 L 400,400 L 0,400 Z' fill='%23ffffff' opacity='0.3'/><text x='200' y='120' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='bold' font-size='22'>Ocean Serenade</text></svg>",
      dominantColor: "#06b6d4",
      accentColor: "#38bdf8",
      audioUrl: "https://cdn.pixabay.com/download/audio/2022/02/07/audio_d0713b1946.mp3?filename=relaxing-guitar-loop-11234.mp3",
      syntheticFreq: [261.63, 329.63, 392.00, 493.88],
      lyrics: [
        { time: 0, text: "♪ (Acoustic guitar strumming...)", translation: "♪ (அகவுஸ்டிக் கிட்டார் இசை / ध्वनिक गिटार)" },
        { time: 15, text: "Waves rolling gently on the shore", translation: "கடற்கரையில் மெதுவாக உருளும் அலைகள் / किनारे पर धीरे से टकराती लहरें" },
        { time: 35, text: "Sun sinking down forevermore", translation: "சூரியன் மெல்ல மறைகிறது / सूरज हमेशा के लिए डूब रहा है" }
      ]
    }
  ],

  // --- UI DICTIONARY TRANSLATIONS ---
  translations: {
    en: {
      appName: "Aurora",
      appSub: "// Player",
      searchPlaceholder: "Search title, artist, genre, lyrics...",
      sortDefault: "Sort: Default",
      sortTitle: "Title (A-Z)",
      sortArtist: "Artist (A-Z)",
      sortDuration: "Duration (Shortest)",
      tabAll: "All Tracks",
      tabEnglish: "English 🇬🇧",
      tabHindi: "Hindi 🇮🇳",
      tabTamil: "Tamil 🇮🇳",
      tabLiked: "Liked Songs 💖",
      tabWishlist: "Wishlist 📌",
      tabCustomPlaylists: "My Playlists 🎶",
      createPlaylistBtn: "+ Create Playlist",
      lyricsHeader: "Synced Lyrics",
      lyricModeOriginal: "Original Script",
      lyricModeTrans: "Translation",
      lyricModeDual: "Dual Subtitles",
      equalizerTitle: "3-Band Audio Equalizer",
      eqPresetLabel: "Equalizer Preset:",
      presetFlat: "Flat (Default)",
      presetBass: "Bass Boost",
      presetVocal: "Vocal Boost",
      presetTreble: "Treble Boost",
      presetPop: "Pop",
      presetRock: "Rock",
      presetElectro: "Electronic",
      eqBass: "Bass",
      eqMid: "Mid",
      eqTreble: "Treble",
      shortcutsTitle: "Keyboard Shortcuts",
      creditsTitle: "Music Credits & Licensing",
      creditsText: "All audio tracks in Aurora are royalty-free under Creative Commons or Pixabay Music licenses with dynamic Web Audio synthesis fallback.",
      sleepTimerTitle: "Sleep Timer",
      sleepTimerOff: "Off",
      sleepTimer15: "15 Minutes",
      sleepTimer30: "30 Minutes",
      sleepTimer45: "45 Minutes",
      sleepTimer60: "60 Minutes",
      sleepTimerActive: "Sleep timer set for",
      speedTitle: "Speed:",
      themeTitle: "Theme:",
      themeAurora: "Aurora Midnight",
      themeCyber: "Cyber Neon",
      themeGold: "Tamil Temple Gold",
      themeEmerald: "Emerald Oasis",
      themeRuby: "Sunset Ruby",
      dragDropHint: "Drag & Drop local MP3 files here to add to playlist",
      noTracksFound: "No tracks found matching your query.",
      toastLiked: "Added to Liked Songs",
      toastUnliked: "Removed from Liked Songs",
      toastWishlistAdded: "Added to Wishlist 📌",
      toastWishlistRemoved: "Removed from Wishlist",
      toastShuffleOn: "Shuffle Enabled",
      toastShuffleOff: "Shuffle Disabled",
      toastRepeatMode: "Repeat Mode:",
      toastLangSwitched: "Language changed to",
      toastThemeSwitched: "Theme changed to",
      playlistCreated: "New Playlist Created:"
    },
    ta: {
      appName: "அரோரா",
      appSub: "// இசை பிளேயர்",
      searchPlaceholder: "பாடல், கலைஞர், வகை தேடுக...",
      sortDefault: "வரிசை: இயல்புநிலை",
      sortTitle: "தலைப்பு (அ-ஃ)",
      sortArtist: "கலைஞர் (அ-ஃ)",
      sortDuration: "கால அளவு (குறைந்தது)",
      tabAll: "அனைத்து பாடல்கள்",
      tabEnglish: "ஆங்கிலம் 🇬🇧",
      tabHindi: "ஹிந்தி 🇮🇳",
      tabTamil: "தமிழ் 🇮🇳",
      tabLiked: "விருப்பமானவை 💖",
      tabWishlist: "உள்விருப்பப் பட்டியல் 📌",
      tabCustomPlaylists: "என் பிளேலிஸ்ட்கள் 🎶",
      createPlaylistBtn: "+ புதிய பிளேலிஸ்ட்",
      lyricsHeader: "ஒத்திசைக்கப்பட்ட வரிகள்",
      lyricModeOriginal: "மூல வரிகள்",
      lyricModeTrans: "ஆங்கில மொழியாக்கம்",
      lyricModeDual: "இருமொழி வரிகள்",
      equalizerTitle: "3-பேண்ட் ஆடியோ ஈக்வலைசர்",
      eqPresetLabel: "ஈக்வலைசர் முன்னமைப்பு:",
      presetFlat: "சாதாரண (Flat)",
      presetBass: "பேஸ் பூஸ்ட் (Bass)",
      presetVocal: "குரல் பூஸ்ட் (Vocal)",
      presetTreble: "ட்ரெபிள் பூஸ்ட் (Treble)",
      presetPop: "பாப் (Pop)",
      presetRock: "ராக் (Rock)",
      presetElectro: "எலக்ட்ரானிக்",
      eqBass: "பேஸ் (Bass)",
      eqMid: "மிட் (Mid)",
      eqTreble: "ட்ரெபிள் (Treble)",
      shortcutsTitle: "விசைப்பலகை குறுக்குவழிகள்",
      creditsTitle: "இசை உரிமங்கள் & கடன் விவரம்",
      creditsText: "அரோராவில் உள்ள அனைத்துப் பாடல்களும் கிரியேட்டிவ் காமன்ஸ் அல்லது பிக்சாபே உரிமத்தின்கீழ் முற்றிலும் இலவசமானவை.",
      sleepTimerTitle: "ஸ்லீப் டைமர் (உறக்கக் கடிகாரம்)",
      sleepTimerOff: "ஆஃப்",
      sleepTimer15: "15 நிமிடங்கள்",
      sleepTimer30: "30 நிமிடங்கள்",
      sleepTimer45: "45 நிமிடங்கள்",
      sleepTimer60: "60 நிமிடங்கள்",
      sleepTimerActive: "ஸ்லீப் டைமர் அமைக்கப்பட்டது:",
      speedTitle: "வேகம்:",
      themeTitle: "தீம்:",
      themeAurora: "அரோரா மிட்நைட்",
      themeCyber: "சைபர் நியான்",
      themeGold: "தமிழ் கோவில் கோல்ட்",
      themeEmerald: "எமரால்டு சோலை",
      themeRuby: "சூரிய அஸ்தமன ரூபி",
      dragDropHint: "உங்கள் MP3 கோப்புகளை இங்கே இழுத்து வந்து சேர்க்கலாம்",
      noTracksFound: "உங்கள் தேடலுக்கு ஏற்ற பாடல்கள் எதுவும் கிடைக்கவில்லை.",
      toastLiked: "விருப்பப் பாடல்களில் சேர்க்கப்பட்டது",
      toastUnliked: "விருப்பப் பாடல்களிலிருந்து நீக்கப்பட்டது",
      toastWishlistAdded: "உள்விருப்பப் பட்டியலில் சேர்க்கப்பட்டது 📌",
      toastWishlistRemoved: "உள்விருப்பப் பட்டியலிலிருந்து நீக்கப்பட்டது",
      toastShuffleOn: "ஷஃபிள் இயக்கப்பட்டது",
      toastShuffleOff: "ஷஃபிள் முடக்கப்பட்டது",
      toastRepeatMode: "மீண்டும் இயக்கும் முறை:",
      toastLangSwitched: "மொழி மாற்றப்பட்டது:",
      toastThemeSwitched: "தீம் மாற்றப்பட்டது:",
      playlistCreated: "புதிய பிளேலிஸ்ட் உருவாக்கப்பட்டது:"
    },
    hi: {
      appName: "अरोरा",
      appSub: "// म्यूजिक प्लेयर",
      searchPlaceholder: "गीत, कलाकार, शैली खोजें...",
      sortDefault: "क्रम: डिफ़ॉल्ट",
      sortTitle: "शीर्षक (A-Z)",
      sortArtist: "कलाकार (A-Z)",
      sortDuration: "अवधि (सबसे छोटा)",
      tabAll: "सभी गाने",
      tabEnglish: "अंग्रेजी 🇬🇧",
      tabHindi: "हिंदी 🇮🇳",
      tabTamil: "तमिल 🇮🇳",
      tabLiked: "पसंदीदा गाने 💖",
      tabWishlist: "विशलिस्ट 📌",
      tabCustomPlaylists: "मेरी प्लेलिस्ट 🎶",
      createPlaylistBtn: "+ नई प्लेलिस्ट",
      lyricsHeader: "सिंक्रनाइज़ बोल (Lyrics)",
      lyricModeOriginal: "मूल पाठ",
      lyricModeTrans: "अंग्रेजी अनुवाद",
      lyricModeDual: "द्विभाषी बोल",
      equalizerTitle: "3-बैंड ऑडियो इक्वलाइज़र",
      eqPresetLabel: "इक्वलाइज़र प्रीसेट:",
      presetFlat: "सामान्य (Flat)",
      presetBass: "बास बूस्ट (Bass)",
      presetVocal: "वोकल बूस्ट (Vocal)",
      presetTreble: "ट्रेबल बूस्ट (Treble)",
      presetPop: "पॉप (Pop)",
      presetRock: "रॉक (Rock)",
      presetElectro: "इलेक्ट्रॉनिक",
      eqBass: "बास",
      eqMid: "मिड",
      eqTreble: "ट्रेबल",
      shortcutsTitle: "कीबोर्ड शॉर्टकट्स",
      creditsTitle: "संगीत क्रेडिट और लाइसेंस",
      creditsText: "अरोरा म्यूजिक प्लेयर में सभी ट्रैक क्रिएटिव कॉमन्स या पिक्साबे लाइसेंस के तहत 100% रॉयल्टी-मुक्त हैं।",
      sleepTimerTitle: "स्लीप टाइमर",
      sleepTimerOff: "बंद",
      sleepTimer15: "15 मिनट",
      sleepTimer30: "30 मिनट",
      sleepTimer45: "45 मिनट",
      sleepTimer60: "60 मिनट",
      sleepTimerActive: "स्लीप टाइमर सेट किया गया:",
      speedTitle: "गति:",
      themeTitle: "थीम:",
      themeAurora: "अरोरा मिडनाइट",
      themeCyber: "साइबर नियॉन",
      themeGold: "तमिल टेंपल गोल्ड",
      themeEmerald: "एमराल्ड ओएसिस",
      themeRuby: "सनसेट रूबी",
      dragDropHint: "प्लेलिस्ट में जोड़ने के लिए अपनी MP3 फ़ाइलों को यहाँ ड्रैग एंड ड्रॉप करें",
      noTracksFound: "आपकी खोज से मेल खाने वाला कोई ट्रैक नहीं मिला।",
      toastLiked: "पसंदीदा गानों में जोड़ा गया",
      toastUnliked: "पसंदीदा गानों से हटाया गया",
      toastWishlistAdded: "विशलिस्ट में जोड़ा गया 📌",
      toastWishlistRemoved: "विशलिस्ट से हटाया गया",
      toastShuffleOn: "सफ़ल चालू",
      toastShuffleOff: "सफ़ल बंद",
      toastRepeatMode: "पुनरावृत्ति मोड:",
      toastLangSwitched: "भाषा बदल दी गई है:",
      toastThemeSwitched: "थीम बदल दी गई है:",
      playlistCreated: "नई प्लेलिस्ट बनाई गई:"
    },
    es: {
      appName: "Aurora",
      appSub: "// Reproductor",
      searchPlaceholder: "Buscar título, artista, género...",
      sortDefault: "Orden: Predeterminado",
      sortTitle: "Título (A-Z)",
      sortArtist: "Artista (A-Z)",
      sortDuration: "Duración (Más corta)",
      tabAll: "Todas",
      tabEnglish: "Inglés 🇬🇧",
      tabHindi: "Hindi 🇮🇳",
      tabTamil: "Tamil 🇮🇳",
      tabLiked: "Favoritas 💖",
      tabWishlist: "Lista de Deseos 📌",
      tabCustomPlaylists: "Mis Listas 🎶",
      createPlaylistBtn: "+ Crear Lista",
      lyricsHeader: "Letras Sincronizadas",
      lyricModeOriginal: "Texto Original",
      lyricModeTrans: "Traducción",
      lyricModeDual: "Subtítulos Dobles",
      equalizerTitle: "Ecualizador de 3 Bandas",
      eqPresetLabel: "Ajuste Preestablecido:",
      presetFlat: "Plano (Predeterminado)",
      presetBass: "Aumento de Graves",
      presetVocal: "Aumento de Voces",
      presetTreble: "Aumento de Agudos",
      presetPop: "Pop",
      presetRock: "Rock",
      presetElectro: "Electrónica",
      eqBass: "Graves",
      eqMid: "Medios",
      eqTreble: "Agudos",
      shortcutsTitle: "Atajos de Teclado",
      creditsTitle: "Créditos de Música",
      creditsText: "Todas las canciones son libres de derechos de autor bajo licencias Creative Commons o Pixabay.",
      sleepTimerTitle: "Temporizador de Apagado",
      sleepTimerOff: "Apagado",
      sleepTimer15: "15 Minutos",
      sleepTimer30: "30 Minutos",
      sleepTimer45: "45 Minutos",
      sleepTimer60: "60 Minutos",
      sleepTimerActive: "Temporizador configurado para",
      speedTitle: "Velocidad:",
      themeTitle: "Tema:",
      themeAurora: "Aurora Medianoche",
      themeCyber: "Ciber Neón",
      themeGold: "Oro Templo Tamil",
      themeEmerald: "Oasis Esmeralda",
      themeRuby: "Rubí Atardecer",
      dragDropHint: "Arrastra y suelta archivos MP3 aquí para añadirlos",
      noTracksFound: "No se encontraron canciones.",
      toastLiked: "Añadido a Favoritas",
      toastUnliked: "Eliminado de Favoritas",
      toastWishlistAdded: "Añadido a Lista de Deseos 📌",
      toastWishlistRemoved: "Eliminado de Lista de Deseos",
      toastShuffleOn: "Aleatorio Activado",
      toastShuffleOff: "Aleatorio Desactivado",
      toastRepeatMode: "Modo Repetición:",
      toastLangSwitched: "Idioma cambiado a",
      toastThemeSwitched: "Tema cambiado a",
      playlistCreated: "Nueva Lista Creada:"
    }
  },

  equalizerPresets: [
    { name: "Flat", gains: [0, 0, 0] },
    { name: "Bass Boost", gains: [8, 2, -2] },
    { name: "Vocal Boost", gains: [-2, 6, 2] },
    { name: "Treble Boost", gains: [-2, 2, 7] },
    { name: "Pop", gains: [3, 5, 2] },
    { name: "Rock", gains: [6, -1, 5] },
    { name: "Electronic", gains: [7, 3, 6] }
  ]
};

Object.freeze(AURORA_DATA);
